services:
  postgres:
    image: postgres:15-alpine
    container_name: taskmate-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskmate
      POSTGRES_USER: taskmate_user
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - taskmate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmate_user -d taskmate"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: taskmate-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taskmate.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - taskmate-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  taskmate-network:
    driver: bridge 